version: '3'
services:
  backend:
    container_name: api
    ports:
      - 3000:3000
    volumes:
      - ./:/var/www/app
    build: .
    depends_on:
      - postgres
    links:
      - postgres
    networks:
      - api
  postgres:
    image: postgres:latest
    env_file:
      - ./database/env
    networks:
      - api
    ports:
      - "55432:5432"
networks:
  api: